import {
  ArrowRightOutlined,
  UserOutlined,
  LockOutlined,
  MobileOutlined,
  CodeSandboxOutlined,
  ApartmentOutlined,
  AimOutlined,
  InsertRowAboveOutlined,
  SmileOutlined,
  AccountBookOutlined,
  DashboardOutlined,
  LineChartOutlined,
  TeamOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  DatabaseOutlined,
  WalletOutlined,
  BarChartOutlined,
  FileAddOutlined,
  DeleteOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  ReloadOutlined,
  FormOutlined,
  CopyOutlined,
  ApiOutlined,
  CloseCircleOutlined,
} from '@ant-design/icons';

export default {
  arrRowRight: <ArrowRightOutlined />,
  userIcon: <UserOutlined />,
  passwordIcon: <LockOutlined />,
  mobileIcon: <MobileOutlined />,
  codeIcon: <CodeSandboxOutlined />,
  department: <ApartmentOutlined />,
  level: <AimOutlined />,
  assessment: <InsertRowAboveOutlined />,
  reward: <SmileOutlined />,
  salary: <AccountBookOutlined />,
  dashboard: <DashboardOutlined />,
  attendance: <LineChartOutlined />,
  team: <TeamOutlined />,
  leftArrow: <MenuFoldOutlined />,
  rightArrow: <MenuUnfoldOutlined />,
  rewardAndPunishment: <DatabaseOutlined />,
  signOut: <WalletOutlined />,
  'bar-chart': <BarChartOutlined />,
  add: <FileAddOutlined />,
  api: <ApiOutlined />,
  del: <DeleteOutlined />,
  close: <CloseCircleOutlined />,
  left: <CaretLeftOutlined />,
  reload: <ReloadOutlined />,
  right: <CaretRightOutlined />,
  detail: <FormOutlined />,
  copy: <CopyOutlined />,
};
